### ISSUE TITLE
Crash: Illegal Argument Exception

### ISSUE THREAD

**Issue by esKaayY** [iguanaman/IguanaTweaksTConstruct#1]
Have done it many times before but his time it crashed: All I did was mine Tin Ore (IC2 version IF it matters) with my Bronze Pickaxe Head (mastered XP).

Crash Log: http://pastebin.com/QAnecNMn
Forge Log: http://www.mediafire.com/?55r8t1mhon23tbe
(ignore TiC spam of conflict IDs. There really isn't any, its AM2, Highlands, and Powersuits that wanna conflict with themselves. I'll bug the TiC team about this also.) 

Iguana Tweaks Version: 1.6.X 1-m
TiC Version: (stable) 1.5.0.2

Edit: Just went back into the world and it happens every time I mine a block (any block, not just tin now). Will post screenshots of the pick.

Edit2: Here is the "new" pickaxe after the crash. Before, It's XP level was Master, it actually displayed Haste (50/50), Luck(x/450 - No idea, it was a random benefit after I lvled it up once), and AutoRepair in the tool tip. The pickaxe still looks like it has those modifiers (based on the picture) but as I crash everytime I mine, its impossible to test. And, as you can see, I can't even see that it has those modifiers or anything in both my inventory and the tool station/forge, it may or not be purely aesthetic. Also notice how it has fortune II on it.

http://imgur.com/9xZvxmv

If you need anything else let me know.

**Comment by sshawnsamuell** [comment]
Came with the same crash. Log is nearly identical.
Quickest way I've been able to recreate is to try and chop down two BoP sacred oaks with a Lumber Axe.
Axe levels to master first time, second tree will crash and erase the Tweak tooltips.

**Comment by esKaayY** [comment]
Yes! I was also able to replicate it again with a different pick. It appears to be some time after obtaining master XP level and you just keep mining/chopping blocks.

**Comment by iguanaman** [comment]
All fixed in the latest version (1n).  Sorry about that people, thanks for reporting the bug here.

**Comment by esKaayY** [comment]
Not a problem! Thanks for the quick fix
